# disable blank issue creation
blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Second-Hand-Friends/kleinanzeigen-bot/discussions
    about: Please ask and answer questions here.
